- name: Configure Elasticsearch
  hosts: elasticsearch
  become: yes
  tasks:
    - name: Add Elasticsearch GPG key
      apt_key:
        url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
        state: present
    - name: Add Elasticsearch repository
      apt_repository:
        repo: "deb https://artifacts.elastic.co/packages/8.x/apt stable main"
        state: present
        filename: elasticsearch
    - name: Install Elasticsearch
      apt:
        name: elasticsearch
        state: latest
    - name: Configure Elasticsearch
      copy:
        src: files/elasticsearch.yml
        dest: /etc/elasticsearch/elasticsearch.yml
        owner: root
        group: elasticsearch
        mode: '0660'
      notify: restart elasticsearch
    - name: Start Elasticsearch
      service:
        name: elasticsearch
        state: started
        enabled: yes
  handlers:
    - name: restart elasticsearch
      service:
        name: elasticsearch
        state: restarted
